exclude: ^(example/|.venv/|code-index.egg-info/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer     # 确保文件以一个空行结尾
      - id: check-yaml            # 检查 YAML 文件语法
      - id: check-toml            # 检查 TOML 文件语法

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.4
    hooks:
      - id: uv-sync
        args: ["--locked", "--all-packages", "--all-groups"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix]
      # Run the formatter
      - id: ruff-format


  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: uv run pytest tests
        language: python
        # 每次都运行完整的测试套件
        pass_filenames: false
        stages: [pre-commit]
        # 即使没有 .py 文件被修改，也会运行
        always_run: true
