name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual workflow dispatch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Setup Python
      run: uv python install

    - name: Install dependencies
      run: |
        uv sync --group dev

    - name: Run tests
      run: |
        uv run pytest tests/ -v